/*
 * Copyright 2024 Confluent Inc.
 */

package io.confluent.flink.udf.adapter.codegen;

/**
 * Interface through which adapters generated by {@link ScalarFunctionAdapterGenerator} can be
 * invoked by client code.
 */
public interface ScalarFunctionCallAdapter {
    Object call(Object instance, Object[] args) throws Throwable;
}
