/*
 * Copyright 2023 Confluent Inc.
 */

package io.confluent.flink.jobgraph;

import java.util.List;

/** Generate the JobGraph from the given arguments. */
public interface JobGraphGenerator {
    /**
     * Generate the JobGraph from the given arguments. For SQL, the arguments would contain a
     * CompiledPlan.
     *
     * <p>After the graph is generated by this method, it will be adjusted by setting savepoint path
     * and initial job requirements and submitted for execution.
     *
     * @param arguments the arguments passed from SQL service via FCP.
     * @param downloader that should be used to download any argument payload if needed
     * @return a JobGraph (wrapped for version compatibility)
     */
    JobGraphWrapper generateJobGraph(List<String> arguments, Downloader downloader);
}
