/*
 * Copyright 2023 Confluent Inc.
 */

package io.confluent.flink.jobgraph;

import java.util.List;
import java.util.Map;

/** Generate the JobGraph from the given arguments. */
public interface JobGraphGenerator {
    /**
     * Generate the JobGraph from the given arguments. For Streaming SQL, the arguments would
     * contain a CompiledPlan.
     *
     * <p>After the graph is generated by this method, it will be adjusted by setting savepoint path
     * and initial job requirements and submitted for execution.
     *
     * @param arguments the arguments passed from SQL service via FCP.
     * @param downloader that should be used to download any argument payload if needed
     * @param metaInfo arbitrary information about this submission that might be necessary to
     *     execute the job. For example: Identity Pool ID, Compute Pool ID for Authorization. JSS
     *     will also set these on Job Configuration
     * @return a JobGraph (wrapped for version compatibility)
     */
    JobGraphWrapper generateJobGraph(
            List<String> arguments, Downloader downloader, Map<String, String> metaInfo);
}
