/*
 * Copyright 2023 Confluent Inc.
 */

package io.confluent.flink.jobgraph.v2;

import io.confluent.flink.jobgraph.JobGraphWrapper;

import java.util.List;
import java.util.Map;

/** Generate the JobGraph from the given arguments. */
public interface JobGraphGeneratorV2 {

    /**
     * Generate the JobGraph from the given arguments. For Streaming SQL, the arguments would
     * contain a CompiledPlan.
     *
     * <p>After the graph is generated by this method, it will be adjusted by setting savepoint path
     * and initial job requirements and submitted for execution.
     *
     * @param arguments the arguments passed from SQL service via FCP.
     * @param generatorConfiguration flink configuration used during job graph generation
     */
    JobGraphWrapper generateJobGraph(
            List<String> arguments, Map<String, String> generatorConfiguration);
}
